#!/bin/bash

CLICK_MODE=true
UNDERLINE_MODE=false
POWERLINE_MODE=false
# Colors

BG=$(xrdb -query | grep -i background: | tail -c 8)
FG=$(xrdb -query | grep -i foreground: | tail -c 8)

BLACK=$(xrdb -query | grep -i color0: | tail -c 8)
BBLACK=$(xrdb -query | grep -i color8: | tail -c 8)

RED=$(xrdb -query | grep -i color1: | tail -c 8)
BRED=$(xrdb -query | grep -i color9: | tail -c 8)

GREEN=$(xrdb -query | grep -i color2: | tail -c 8)
BGREEN=$(xrdb -query | grep -i color10: | tail -c 8)

YELLOW=$(xrdb -query | grep -i color3: | tail -c 8)
BYELLOW=$(xrdb -query | grep -i color11: | tail -c 8)

BLUE=$(xrdb -query | grep -i color4: | tail -c 8)
BBLUE=$(xrdb -query | grep -i color12: | tail -c 8)

MAGENTA=$(xrdb -query | grep -i color5: | tail -c 8)
BMAGENTA=$(xrdb -query | grep -i color13: | tail -c 8)

CYAN=$(xrdb -query | grep -i color6: | tail -c 8)
BCYAN=$(xrdb -query | grep -i color14: | tail -c 8)

WHITE=$(xrdb -query | grep -i color7: | tail -c 8)
BWHITE=$(xrdb -query | grep -i color15: | tail -c 8)

# Bar colors
BAR_BG="00${WHITE}"
BAR_FG=${BG}
# FOC_FG=${BGREEN}
FOC_FG=${BLUE}
FOC_BG=${BWHITE}
ACT_FG=${BWHITE}
ACT_BG=${BG}
MOD_FG=${BWHITE}
MOD_BG=${MAGENTA}
MUSIC_FG=${BG}
MUSIC_BG=${BWHITE}
DATE_FG=${WHITE}
DATE_BG=${BG}
DATE_ICON_FG=${BG}
TIME_FG=${WHITE}
TIME_BG=${BG}
TIME_ICON_FG=${DATE_ICON_FG}
VOL_FG=${WHITE}
VOL_BG=${BG}
VOL_ICON_FG=${DATE_ICON_FG}
POWER_FG=${BLUE}
POWER_BG=${BWHITE}
UNDERLINE=${BG}

# Icons
if [ "$POWERLINE_MODE" = true ]; then
    SEP_R=""
    SEP_L=""
    SEP_R_L=""
    SEP_L_L=""
else
    SEP_R=" "
    SEP_L=" "
    SEP_R_L=" "
    SEP_L_L=" "
fi

PLAY_ICON=""
PAUSE_ICON=""
CALENDAR_ICON=""
TIME_ICON=""
VOL_UP_ICON=""
VOL_DOWN_ICON=""
VOL_OFF_ICON=""
WIFI_ICON=""
POWER_ICON=""

DATE_TIMER=1
CLOCK_TIMER=1

# Fonts
FONT1="source code pro for powerline:regular:size=9"
FONT2="Font Awesome:regular:size=10"
FONT3="source code pro for powerline:regular:size=12"

FONT1_OFFSET=-3
FONT2_OFFSET=-4
FONT3_OFFSET=0

# Wifi interface
DEVICE=$(iw dev | grep Interface | awk '{print $2}')

# Song section max length
SONG_MAX_LENGTH=30

# gaps
H_GAP=20
V_GAP=10

# Size
BAR_HEIGHT=22
# BAR_LENGTH=$(($(xrandr | grep '*' | awk -F'x' '{print $1}') - H_GAP * 2))
